#Wednesday, September 23, 2026 19:30:00 GMT
android.enableAppCompileTimeRClass=true
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.incremental.native=true

# -XX:+UseG1GC -XX:+DisableExplicitGC
# -XX:+UseZGC
org.gradle.jvmargs=-Xms4096M -Xmx8300m -Dfile.encoding\=UTF-8 -XX:+UseZGC

android.suppressUnsupportedCompileSdk=37.0
