#Friday, September 11, 2026 12:00:00 GMT
android.enableAppCompileTimeRClass=true
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.incremental.native=true

# -XX:+UseG1GC -XX:+DisableExplicitGC
# -XX:+UseZGC
org.gradle.jvmargs=-Xms4096M -Xmx7200m -Dfile.encoding\=UTF-8 -XX:+UseZGC

android.suppressUnsupportedCompileSdk=37.0

BUILDTOOLS_VERSION=37.0.0
NDK_VERSION=29.0.14206865
CMAKE_VERSION=4.4.2
COMPILE_SDK=37
MIN_SDK=24
TARGET_SDK=37
VERSION_CODE=25
VERSION_PREFIX=4.2
