name: Android CI

on:
  push:
    branches: [ "neko" ]
  pull_request:
    branches: [ "neko" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup CMake
        uses: lukka/get-cmake@v4.4.2
        with:
          useLocalCache: false
          useCloudCache: true

      - name: Check CMake Version
        run: cmake --version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystores
        run: |
          echo "${{ secrets.OLD_SIGNING_KEY_BASE64 }}" | base64 --decode > app/bash/old_key.jks
          echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 --decode > app/bash/new_key.jks
          echo "${{ secrets.SIGNING_KEYS_BASE64 }}" | base64 --decode > app/bash/new_keys.jks
          echo "${{ secrets.SIGNING_PQC_KEY_BASE64 }}" | base64 --decode > app/bash/pqc_key.jks
          echo "${{ secrets.LINEAGE_A_BASE64 }}" | base64 --decode > app/bash/app_lineage_1.bin
          echo "${{ secrets.LINEAGE_B_BASE64 }}" | base64 --decode > app/bash/app_lineage_2.bin
          echo "${{ secrets.LINEAGE_C_BASE64 }}" | base64 --decode > app/bash/app_lineage_3.bin

      - name: Build Debug, Release and Bundle
        run: ./gradlew :app:lint :app:assembleDebug :app:assembleRelease :app:bundleDebug :app:bundleRelease -i -w --stacktrace --warning-mode all 2>&1 | tee build.log
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          
      - name: Upload Build Log
        uses: actions/upload-artifact@v7
        with:
          name: build-log
          path: build.log
          archive: false
          
      - name: Upload Lint Report HTML
        uses: actions/upload-artifact@v7
        with:
          name: lint-reports-html
          path: app/build/reports/lint-results-debug.html
          archive: false
          
      - name: Upload Lint Report
        uses: actions/upload-artifact@v7
        with:
          name: lint-reports
          path: app/build/reports/*
          archive: true
        
      - name: Upload Native Debug Symbols
        uses: actions/upload-artifact@v7
        with:
          name: native-debug-symbols
          path: app/build/outputs/native-debug-symbols/release/native-debug-symbols.zip
          archive: false
          
      - name: Upload Debug Manifest
        uses: actions/upload-artifact@v7
        with:
          name: manifest-debug
          path: app/build/outputs/logs/manifest-merger-debug-report.txt
          archive: false
          
      - name: Upload Release Manifest
        uses: actions/upload-artifact@v7
        with:
          name: manifest-release
          path: app/build/outputs/logs/manifest-merger-release-report.txt
          archive: false
         
      - name: Upload R8
        uses: actions/upload-artifact@v7
        with:
          name: r8-deploy
          path: app/build/outputs/mapping/release/*
          archive: true
          
      - name: Upload R8 HTML
        uses: actions/upload-artifact@v7
        with:
          name: r8-html
          path: app/build/outputs/mapping/release/configanalyzer.html
          archive: false
      
      - name: Upload Debug Bundle
        uses: actions/upload-artifact@v7
        with:
          name: aab-bundle-debug
          path: app/build/outputs/bundle/debug/app-debug.aab
          archive: false
          
      - name: Upload Release Bundle
        uses: actions/upload-artifact@v7
        with:
          name: aab-bundle-release
          path: app/build/outputs/bundle/release/app-release.aab
          archive: false
          
      - name: Upload Debug APKs
        uses: actions/upload-artifact@v7
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*
          archive: true

      - name: Upload Release APKs
        uses: actions/upload-artifact@v7
        with:
          name: app-release
          path: app/build/outputs/apk/release/*
          archive: true
          
      - name: Sign APKs
        run: |
          chmod +x app/bash/app_sign_apk.sh
          ./app/bash/app_sign_apk.sh
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          OLD_KEY_STORE_PASSWORD: ${{ secrets.OLD_KEY_STORE_PASSWORD }}
          OLD_KEY_ALIAS: ${{ secrets.OLD_KEY_ALIAS }}
          OLD_KEY_PASSWORD: ${{ secrets.OLD_KEY_PASSWORD }}
          NEW_KEY_STORE_PASSWORD: ${{ secrets.NEW_KEY_STORE_PASSWORD }}
          NEW_KEY_ALIAS: ${{ secrets.NEW_KEY_ALIAS }}
          NEW_KEY_PASSWORD: ${{ secrets.NEW_KEY_PASSWORD }}
          PQC_KEY_STORE_PASSWORD: ${{ secrets.PQC_KEY_STORE_PASSWORD }}
          PQC_KEY_ALIAS: ${{ secrets.PQC_KEY_ALIAS }}
          PQC_KEY_PASSWORD: ${{ secrets.PQC_KEY_PASSWORD }}
          
      - name: Upload Debug Sign APKs
        uses: actions/upload-artifact@v7
        with:
          name: app-debug-sign
          path: app/sign/debug/*
          archive: true

      - name: Upload Release Sign APKs
        uses: actions/upload-artifact@v7
        with:
          name: app-release-sign
          path: app/sign/release/*
          archive: true
      
      - name: Builds Splits APKs
        run: |
          chmod +x app/bash/app_apks_sign.sh
          ./app/bash/app_apks_sign.sh
        env:
          GH_TOKEN: ${{ github.token }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          OLD_KEY_STORE_PASSWORD: ${{ secrets.OLD_KEY_STORE_PASSWORD }}
          OLD_KEY_ALIAS: ${{ secrets.OLD_KEY_ALIAS }}
          OLD_KEY_PASSWORD: ${{ secrets.OLD_KEY_PASSWORD }}
          NEW_KEY_STORE_PASSWORD: ${{ secrets.NEW_KEY_STORE_PASSWORD }}
          NEW_KEY_ALIAS: ${{ secrets.NEW_KEY_ALIAS }}
          NEW_KEY_PASSWORD: ${{ secrets.NEW_KEY_PASSWORD }}
          PQC_KEY_STORE_PASSWORD: ${{ secrets.PQC_KEY_STORE_PASSWORD }}
          PQC_KEY_ALIAS: ${{ secrets.PQC_KEY_ALIAS }}
          PQC_KEY_PASSWORD: ${{ secrets.PQC_KEY_PASSWORD }}
          
      - name: Upload Splits Debug APKs
        uses: actions/upload-artifact@v7
        with:
          name: apks-bundle-debug
          path: app/build/outputs/bundle/debug/app-debug.apks
          archive: false
          
      - name: Upload Splits Release APKs
        uses: actions/upload-artifact@v7
        with:
          name: apks-bundle-release
          path: app/build/outputs/bundle/release/app-release.apks
          archive: false